apiVersion: v1
kind: Service
metadata:
  name: crudbooks-service
  labels:
    app: crudbooks
spec:
  type: NodePort
  selector:
    app: crudbooks
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
